version: ~> 1.0
import: scala/scala-dev:travis/default.yml

language: scala
env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11
scala:
  - 3.0.0-RC2
  - 2.12.13
  - 2.13.5

before_install:
  - git fetch --tags

script:
  - sbt ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues package
  - git diff --exit-code # check scalariform

stages:
  - name: release
    if: (tag IS present) AND NOT fork AND env(ADOPTOPENJDK) = 8

jobs:
  include:
    - stage: release
      script: sbt ci-release

notifications:
  email:
  - seth.tisue@lightbend.com
